### ISSUE TITLE
[1.16.5] Huge FPS drop / lag when going into the Game Menu (hitting ESC in-game), when customization of that menu is on.

### ISSUE THREAD

**Issue by Gbergz** [Keksuccino/FancyMenu-Support#163] opened 2021-04-17 14:31 UTC
**Describe the bug**
There's a huge fps drop / lag when going into the Game Menu (hitting ESC in-game), when customization of that menu is on.

**More Info**
I've tested this on a clean instance with just FancyMenu (& Konkrete) it doesn't seem to be present. 
Though in a heavy modded environment with 250+ mods the lag is there, very much present and annoying. The lag is also present when trying to rescale the minecraft window. It's lagging alot. 
note: This also happens in the Main Menu, where resizing the window is annoying due to the lag.

**To Reproduce**
1. Be in an environment with 250+ mods.
2. Enable Customization on a menu. (ingame for example)
3. Add something, like a button for testing.
4. Save it. Exit it out of customization.
5. Try and hit escape while ingame or resizing the window.
6. Lag/fps drops.

**Expected behavior**
No lag like when customization of a menu is off.

**Crash Log**
No Crashes.

**Videos** (FPS is displayed in large text beside the minimap top right.)

**Videos 1 (Customization of menu ON!):**
In-game hitting escape: https://streamable.com/rzprei
Resizing window: https://streamable.com/stzioy

**Videos 2 (Customization of menu OFF!)**
In-game hitting escape: https://streamable.com/n91yj7
Rezising window: https://streamable.com/i3nvyh

**Video information:**
You can see on video 1 when hitting escape that there's a slight delay and the mouse cursor is shown before the menu actually popping up. Or resizing the window is so laggy.
While on video 2 there's no delay and no lag whatsoever.

**Basic Informations (please complete the following information):**
 - OS Windows
 - FancyMenu Version 2.0.6
 - Forge Version 36.1.2
 - Minecraft Version 1.16.5
 - Other Active Mods: Modpack TNP Limitless 3, Mod list: [[MOD LIST]](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/files/3276731)

**Comment by Keksuccino** [comment] 2021-04-17 15:24
Sorry to hear that, but as you already noticed, it’s caused by one of your mods. It’s a mod conflict.
I'm very sorry, but I don’t have time to check 250+ mods, but maybe there are errors printed to the log that could explain what exactly is going on and maybe which mod is causing it.

Can you please send me your latest.log file?
It’s located at `.minecraft/logs/latest.log`. 

Thank you very much!

**Comment by Gbergz** [comment] 2021-04-17 15:35
[latest.log](https://github.com/Keksuccino/FancyMenu-Support/files/6329525/latest.log)
 This is the log after the game is done booting up and is at the main menu, i did some resizing etc.
 
 Alsom
 Just feels off that its caused by another mod when it only happens when customization of the menu is on.
 
 I can myself try to locate which mod if its indeed caused by one.

**Comment by Gbergz** [comment] 2021-04-17 15:38
I'm in a clean instance now w/ the customizations I've done to the main menu. Only Konkrete + FancyMenu. And the lag is there. Not as much but its there.

**Comment by Keksuccino** [comment] 2021-04-17 15:40
Did you used any web elements there? Like web text or web images?

**Comment by Gbergz** [comment] 2021-04-17 15:40
Yes. There's 3 links. But images are local

**Comment by Keksuccino** [comment] 2021-04-17 15:44
Links like buttons linking to something?

Can you send me your latest.log file and your `fancymenu` folder, located at `.minecraft/config/fancymenu`, please?

**Comment by Gbergz** [comment] 2021-04-17 15:48
Yes the buttons links to my modpacks changelog.
(This one should be in the config folder) [fancymenu config folder.zip](https://github.com/Keksuccino/FancyMenu-Support/files/6329554/fancymenu.config.folder.zip)

(And this one should be in the modpack root folder where, config, logs & the mods folder is locaed) [fancymain modpack root folder.zip](https://github.com/Keksuccino/FancyMenu-Support/files/6329555/fancymain.modpack.root.folder.zip)

**Comment by Keksuccino** [comment] 2021-04-17 15:59
Thank you, will check it asap!

**Comment by Keksuccino** [comment] 2021-04-20 18:19
I wasn't able to reproduce the lag. The heavy lag you had in the videos was definitely caused by a mod.

Without other mods, just FM and Konkrete, there's only a really slightly visible lag, which isn't even really noticeable if you don't know it's there. This small lag is caused by the button caching system which can't be improved more, it already has the best possible performance.

The main menu during my lag test: https://gyazo.com/d8926858cd54a983a3976478ec6df39f
Pause Menu during lag test: https://gyazo.com/4465137da5a95d7a63df98214a6ada0b

**Comment by Gbergz** [comment] 2021-04-20 18:59
Hm strange! 
I added 11 mods. All Mekanism Modules + All the Macaw's Mod just to test with more mods and the lag is there and definitely more noticable aswell. 13 mods in total.

**Video with 13 mods:**
https://streamable.com/eltiad

**Video with 6 mods:**
https://streamable.com/b9x97r

**Comment by Keksuccino** [comment] 2021-04-24 16:05
> I think just adding any mods will make it lag. Absolutely fine with just Fancymenu + Konkrete. But as soon as you add like 5 more mods the lag is very noticable and annoying.

There are modpacks with over 200 mods that work great with FancyMenu. It makes no sense that it's related to the number of mods/mods in general.
I have no clue why this seems to happen for you (I don't think it's lagging too bad in most of your videos, but yeah, it's more noticeable than usual). Maybe it's something related to your game instance or your system, but without anything in the log that could help me, it's basically impossibe to fix it, I'm very sorry :/

**Comment by Gbergz** [comment] 2021-04-24 16:44
> There are modpacks with over 200 mods that work great with FancyMenu.
Yes it works great ofcourse.. it's just that lag/fps drops when resizing the window / entering menus w/ customizations enabled that makes it annoying. Which is why I initially created this report.

I've now downloaded another modpack called "[Better Minecraft Modpack](https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack)" and the lag is present there aswell. Disabling the customizations and its smooth as butter.

So I don't know what to do anymore, and what you can do. Seems impossible to fix you're right ..

**For reference my pc has the specs:** 
GPU: 3080
CPU: i7 8700k @ 4.8ghz
RAM: 32gb (8gb allocated to mc) @ 3200mhz

So I don't really think its the pc either..

**Comment by Keksuccino** [comment] 2021-04-24 18:50
Sure it doesn’t lag when customizations are disabled, because then FM isn’t caching buttons and doing all it’s customizations to the menu before it is displayed ^^ And yes, resizing the window counts as reloading the menu. There will always be a small lag, but you’re not resizing your menu the whole time, so it shouldn’t be too bad.

I will ofc keep trying to optimize the mod performance, but will close this for now. Thank you for your report and sorry that I wasn’t able to really help you.

**Closed by Keksuccino** 2021-04-24 18:50 UTC
Labels: mod incompatibility
